/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.controleequipamentos.Telas;

import br.com.controleequipamentos.classes.DAO.UsuarioDAO;
import br.com.controleequipamentos.classes.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author higor
 */
public class TelaMenu extends javax.swing.JFrame {

    Usuario user = new Usuario();
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    String aux;
  

    /**
     * Creates new form Menu
     */
    public TelaMenu(String nome) {
        initComponents();
        aux = nome;
    }

    private TelaMenu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCadastroEquipamento = new javax.swing.JButton();
        jButtonBuscaEquipamento = new javax.swing.JButton();
        jButtonManutencao = new javax.swing.JButton();
        jButtonGerenciamentoManutencao = new javax.swing.JButton();
        jButtonEditaPerfil = new javax.swing.JButton();
        jButtonCadastraTipoEquipamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtonCadastroEquipamento.setText("CADASTRAR EQUIPAMENTO");
        jButtonCadastroEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroEquipamentoActionPerformed(evt);
            }
        });

        jButtonBuscaEquipamento.setText("BUSCAR EQUIPAMENTO");

        jButtonManutencao.setText("ABERTURA DE MANUTENÇÃO");
        jButtonManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManutencaoActionPerformed(evt);
            }
        });

        jButtonGerenciamentoManutencao.setText("GERENCIAMENTO DE MANUTENÇÃO");

        jButtonEditaPerfil.setText("EDITAR PERFIL");
        jButtonEditaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditaPerfilActionPerformed(evt);
            }
        });

        jButtonCadastraTipoEquipamento.setText("CADASTRAR TIPOS DE EQUIPAMENTOS");
        jButtonCadastraTipoEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraTipoEquipamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCadastroEquipamento)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGerenciamentoManutencao)
                            .addComponent(jButtonCadastraTipoEquipamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscaEquipamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEditaPerfil, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonManutencao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonBuscaEquipamento, jButtonCadastraTipoEquipamento, jButtonCadastroEquipamento, jButtonEditaPerfil, jButtonGerenciamentoManutencao, jButtonManutencao});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroEquipamento)
                    .addComponent(jButtonBuscaEquipamento))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditaPerfil)
                    .addComponent(jButtonCadastraTipoEquipamento))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonManutencao)
                    .addComponent(jButtonGerenciamentoManutencao))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonBuscaEquipamento, jButtonCadastraTipoEquipamento, jButtonCadastroEquipamento, jButtonEditaPerfil, jButtonGerenciamentoManutencao, jButtonManutencao});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroEquipamentoActionPerformed
        // TODO add your handling code here:
        if (usuarioDAO.controleAcessoUsuarioSecretaria(aux) == true) {
            if (new TelaCadastroEquipamento(aux) == null) {
               new TelaCadastroEquipamento(aux).setVisible(true);
                new TelaCadastroEquipamento(aux).setResizable(false);
            } else {
                new TelaCadastroEquipamento(aux).setVisible(true);
                new TelaCadastroEquipamento(aux).setResizable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão!");
        }

    }//GEN-LAST:event_jButtonCadastroEquipamentoActionPerformed

    private void jButtonCadastraTipoEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraTipoEquipamentoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (usuarioDAO.controleAcessoUsuarioSecretaria(aux) == true) {
            if (new TelaCadastroTipoEquipamento(aux) == null) {
                new TelaCadastroTipoEquipamento(aux).setVisible(true);
                new TelaCadastroTipoEquipamento(aux).setResizable(false);

            } else {
                new TelaCadastroTipoEquipamento(aux).setVisible(true);
                new TelaCadastroTipoEquipamento(aux).setResizable(false);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão!");
        }
    }//GEN-LAST:event_jButtonCadastraTipoEquipamentoActionPerformed

    private void jButtonManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManutencaoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonManutencaoActionPerformed

    private void jButtonEditaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditaPerfilActionPerformed
        // TODO add your handling code here:
        new TelaEditaCadastro(aux).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonEditaPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscaEquipamento;
    private javax.swing.JButton jButtonCadastraTipoEquipamento;
    private javax.swing.JButton jButtonCadastroEquipamento;
    private javax.swing.JButton jButtonEditaPerfil;
    private javax.swing.JButton jButtonGerenciamentoManutencao;
    private javax.swing.JButton jButtonManutencao;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
